package app.abelsc.com.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MaquinariaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMaquinariaAllPropertiesEquals(Maquinaria expected, Maquinaria actual) {
        assertMaquinariaAutoGeneratedPropertiesEquals(expected, actual);
        assertMaquinariaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMaquinariaAllUpdatablePropertiesEquals(Maquinaria expected, Maquinaria actual) {
        assertMaquinariaUpdatableFieldsEquals(expected, actual);
        assertMaquinariaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMaquinariaAutoGeneratedPropertiesEquals(Maquinaria expected, Maquinaria actual) {
        assertThat(expected)
            .as("Verify Maquinaria auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMaquinariaUpdatableFieldsEquals(Maquinaria expected, Maquinaria actual) {
        assertThat(expected)
            .as("Verify Maquinaria relevant properties")
            .satisfies(e -> assertThat(e.getModelo()).as("check modelo").isEqualTo(actual.getModelo()))
            .satisfies(e -> assertThat(e.getEstado()).as("check estado").isEqualTo(actual.getEstado()))
            .satisfies(e -> assertThat(e.getPrecio()).as("check precio").isEqualTo(actual.getPrecio()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMaquinariaUpdatableRelationshipsEquals(Maquinaria expected, Maquinaria actual) {
        assertThat(expected)
            .as("Verify Maquinaria relationships")
            .satisfies(e -> assertThat(e.getEmpresa()).as("check empresa").isEqualTo(actual.getEmpresa()));
    }
}
