package app.abelsc.com.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MaquinariaObraAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMaquinariaObraAllPropertiesEquals(MaquinariaObra expected, MaquinariaObra actual) {
        assertMaquinariaObraAutoGeneratedPropertiesEquals(expected, actual);
        assertMaquinariaObraAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMaquinariaObraAllUpdatablePropertiesEquals(MaquinariaObra expected, MaquinariaObra actual) {
        assertMaquinariaObraUpdatableFieldsEquals(expected, actual);
        assertMaquinariaObraUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMaquinariaObraAutoGeneratedPropertiesEquals(MaquinariaObra expected, MaquinariaObra actual) {
        assertThat(expected)
            .as("Verify MaquinariaObra auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMaquinariaObraUpdatableFieldsEquals(MaquinariaObra expected, MaquinariaObra actual) {
        assertThat(expected)
            .as("Verify MaquinariaObra relevant properties")
            .satisfies(e -> assertThat(e.getHoras()).as("check horas").isEqualTo(actual.getHoras()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMaquinariaObraUpdatableRelationshipsEquals(MaquinariaObra expected, MaquinariaObra actual) {
        assertThat(expected)
            .as("Verify MaquinariaObra relationships")
            .satisfies(e -> assertThat(e.getObra()).as("check obra").isEqualTo(actual.getObra()))
            .satisfies(e -> assertThat(e.getMaquinaria()).as("check maquinaria").isEqualTo(actual.getMaquinaria()));
    }
}
