package app.abelsc.com.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MaterialObraAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMaterialObraAllPropertiesEquals(MaterialObra expected, MaterialObra actual) {
        assertMaterialObraAutoGeneratedPropertiesEquals(expected, actual);
        assertMaterialObraAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMaterialObraAllUpdatablePropertiesEquals(MaterialObra expected, MaterialObra actual) {
        assertMaterialObraUpdatableFieldsEquals(expected, actual);
        assertMaterialObraUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMaterialObraAutoGeneratedPropertiesEquals(MaterialObra expected, MaterialObra actual) {
        assertThat(expected)
            .as("Verify MaterialObra auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMaterialObraUpdatableFieldsEquals(MaterialObra expected, MaterialObra actual) {
        assertThat(expected)
            .as("Verify MaterialObra relevant properties")
            .satisfies(e -> assertThat(e.getCantidad()).as("check cantidad").isEqualTo(actual.getCantidad()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMaterialObraUpdatableRelationshipsEquals(MaterialObra expected, MaterialObra actual) {
        assertThat(expected)
            .as("Verify MaterialObra relationships")
            .satisfies(e -> assertThat(e.getObra()).as("check obra").isEqualTo(actual.getObra()))
            .satisfies(e -> assertThat(e.getMaterial()).as("check material").isEqualTo(actual.getMaterial()));
    }
}
