package app.abelsc.com.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PerfilUsuarioAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPerfilUsuarioAllPropertiesEquals(PerfilUsuario expected, PerfilUsuario actual) {
        assertPerfilUsuarioAutoGeneratedPropertiesEquals(expected, actual);
        assertPerfilUsuarioAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPerfilUsuarioAllUpdatablePropertiesEquals(PerfilUsuario expected, PerfilUsuario actual) {
        assertPerfilUsuarioUpdatableFieldsEquals(expected, actual);
        assertPerfilUsuarioUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPerfilUsuarioAutoGeneratedPropertiesEquals(PerfilUsuario expected, PerfilUsuario actual) {
        assertThat(expected)
            .as("Verify PerfilUsuario auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPerfilUsuarioUpdatableFieldsEquals(PerfilUsuario expected, PerfilUsuario actual) {
        // empty method

    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPerfilUsuarioUpdatableRelationshipsEquals(PerfilUsuario expected, PerfilUsuario actual) {
        assertThat(expected)
            .as("Verify PerfilUsuario relationships")
            .satisfies(e -> assertThat(e.getEmpresa()).as("check empresa").isEqualTo(actual.getEmpresa()));
    }
}
